name: Send Email on Commit

on:
  push:
    branches:
      - main  # or any branch you want to monitor

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the commit message
        run: echo "Commit message: ${{ github.event.head_commit.message }}" > commit_message.txt

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # or your email provider's SMTP server
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}  # Set up your SMTP username in repo secrets
          password: ${{ secrets.SMTP_PASSWORD }}  # Set up your SMTP password in repo secrets
          subject: "New Commit in GitHub Repo"
          body: |
            There was a new commit in the repository:
            ${{ github.event.head_commit.message }}

            Repository: ${{ github.repository }}
            Committer: ${{ github.event.head_commit.committer.name }}
          to: your-email@example.com
          from: GitHub Repo <github@example.com>
