name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow the token to write to the repository

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Root directory for GitHub Pages

      - name: Notify Deployment Status
        env:
          OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
          OUTLOOK_PASS: ${{ secrets.OUTLOOK_PASS }}
          DEPLOY_STATUS: ${{ job.status }}
          EMAIL_TO: 29henbar@draschools.org  # Recipient's email
        run: |
          # Create email content
          EMAIL_CONTENT="Subject: GitHub Pages Deploy Status\n"
          EMAIL_CONTENT+="Deployment Status: $DEPLOY_STATUS\n"
          EMAIL_CONTENT+="See the deployment at https://buggzradio.github.io/jarbeefis\n"
          EMAIL_CONTENT+="Sending email to: $EMAIL_TO\n"

          # Output email content to a temporary file
          echo -e "$EMAIL_CONTENT" > email.txt

          # Debug: Print the email content to logs
          echo "Email content:"
          cat email.txt

          # Send the email using curl
          curl --url 'smtp://smtp.office365.com:587' --ssl-reqd \
            --mail-from "$OUTLOOK_USER" \
            --mail-rcpt "$EMAIL_TO" \
            --upload-file email.txt \
            --user "$OUTLOOK_USER:$OUTLOOK_PASS" \
            --header "Content-Type: text/plain"
